# Generated by Django 4.1.5 on 2023-03-24 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productline",
            name="product_type",
        ),
    ]
